# DIFERENCIAS FINITAS #

### Cargar módulos necesarios para el programa ###

* En este módulo se llaman las librerías necesarias para la creación del programa. La librería numpy que permite realizar operaciones con matrices o vectores.

In [192]:
import numpy as np  

### Modulo para el valor de las condiciones de frontera ###

* En el siguiente modulo se le pueden ajustar los valores frontera. Únicamente cambiando cada valor frontera se puede resolver el ejercicio de la misma forma para cualquiera de los casos de estudio.

![IMAGE](IM2.png)

In [193]:
a=1#float(input("Ingresar condición inicial superior = "))
c=0#float(input("Ingresar condición inicial inferior = "))
b=0#float(input("Ingresar condición inicial derecha = "))
d=0#float(input("Ingresar condición inicial izquierda = "))

### Número de nodos ###
* En este módulo se pueden ajustar los valores para el número de nodos ***NodosX-NodosY***, y se crea la respectiva matriz que representa el arreglo nodal.
* Se debe tener en cuenta que el número de nodosX y nodosY se puede ajustar a las condiciones que requiere el ejercicio. Es decir para arreglos de 5x5, 11x11 y 31x31 nodos.

In [194]:
NodosX=11  # Número de nodos o particiones para el eje X.
NodosY=11  # Número de nodos o particiones del eje Y.
matriz=np.zeros((NodosX,NodosY))  # Crea una matriz para guardar los datos obtenidos de la matriz del sistema.
malla=np.zeros((NodosX,NodosY))  # Crea una matriz para guardar los valores supuestos de cada iteración.
error=np.zeros((NodosX,NodosY))  # Crea una matriz que guarda el error en cada iteración.

### Calculo de valores supuestos ###
* En este módulo, se realiza el llenado de la matriz para los valores supuestos de cada nodo. Este cálculo se realiza calculando un promedio entre los nodos que relacionan cada sección. Es decir, para los nodos superiores se determina un promedio entre los valores de las fronteras norte, oriente y occidente. Para los valored centrales se realiza un promedio con los valores de los valores de las fronteras oriente y occidente. Por último, para los valores supuestos de la parte interior, se toma un promedio entre los valores de las fronteras sur, oriente y occidente. Esto se realiza porque el método de solución es iterativo y se necesita un valor inicial de aproximación. 

In [195]:
for m in range(0,NodosX-1):
    for n in range(0,NodosY-1):
        
        malla[0,n]=(a+d+b)/3
        malla[m+1,n]=(d+b)/2
        malla[NodosX-1,n]=(b+d+c)/3 

### Calculo de la matriz del sistema ###
* En este módulo se inicia con el método que determinará la matriz del sistema.
* Se pueden ajustar parametros como el número máximo de iteraciones **"max"** y el valor de la **tolerancia** del método.
* El método se inicia clasificando los nodos de acuerdo a su posición en tres regiones, **nodos superiores, centrales e inferiores** de acuerdo al siguente arreglo.
![IMAGE](IM4.png)
* Para los nodos superiores, se clasifican los nodos segun el siguiente arreglo.
![IMAGE](IM5.png)
* Para los nodos de la región central, se procede a clasificarlos segun el siguiente arreglo.
![IMAGE](IM6.png)
* Para los nodos de la región inferior se clasifican segun el siguiente arreglo.
![IMAGE](IM7.png)

In [196]:
for k in range(0,NodosX):       
            for l in range(0,NodosY):

                n=1  # Contador inicial para el ciclo.
                max=100  # Número máximo de iteraciones.
                Tolerancia=1e-3
                               
                while  n<=max:  # Se inicia el ciclo iterativo.
                            
                            for i in range(0,NodosX-2):
                                for j in range(0,NodosY-2):

                                    ## ECUACIONES PARA LOS NODOS SUPERIORES
                                    
                                    matriz[0,0]=(malla[1,0]+a+malla[0,1]+d)/4  # Ecuación que representa el nodo de esquina superior izquiera.   
                                    matriz[0,j+1]=(malla[1,j+1]+a+malla[0,j+1]+matriz[0,j])/4  # Ecuación que representa los nodos centrales superiores.                                             
                                    matriz[0,NodosY-1]=(matriz[0,NodosY-2]+a+b+malla[1,NodosY-1])/4  # Ecuación que representa el nodo de esquina superior derecha. 
                            
                                      
                                    ## ECUACIONES PARA LOS NODOS CENTRALES
                                    
                                    matriz[i+1,0]=(matriz[i,0]+malla[i+2,0]+malla[i+1,1]+d)/4  # Ecuación que representa los nodos de la parte izquierda.                                    
                                    matriz[i+1,j+1]=(malla[i+2,j+1]+matriz[i,j+1]+malla[i+1,j+2]+matriz[i+1,j])/4  # Ecuación que representa los nodos de toda la parte central del arreglo.                                    
                                    matriz[i+1,NodosY-1]=(malla[i+2,NodosY-2]+matriz[i,NodosY-1]+b+matriz[i+1,NodosY-2])/4  # Ecuación que representa los nodos de la parte derecha.
                                            
                            
                                    ## ECUACIONES PARA LOS NODOS INFERIORES
                                    
                                    matriz[NodosX-1,0]=(c+matriz[NodosX-2,0]+malla[NodosX-1,1]+d)/4  # Ecuación que representa el nodo inferior izquierdo.                                    
                                    matriz[NodosX-1,j+1]=(c+matriz[NodosX-2,j+1]+malla[NodosX-1,j+2]+matriz[NodosX-1,j])/4  # Ecuación que representa los nodos centrales inferiores.                                   
                                    matriz[NodosX-1,NodosY-1]=(c+matriz[NodosX-2,NodosY-1]+b+matriz[NodosX-1,NodosY-2])/4  # Ecuación que representa el nodo inferior derecha.
                               
                                    
                                    error[k,l]=(malla[k,l]-matriz[k,l])  # Cálculo del error entre el valor calculado y el supuesto.
                                    ERR=abs(sum(sum(error))) # Error total en la iteración.
                                    n=n+1  # Contador para el ciclo ("necesario para determinar el número de iteraciones mínimas segun tolerancia requerida")
                                    malla[k,l]=matriz[k,l]  # Si la tolerancia no es la requerida, se inicia el ciclo pero ahora los valores supuestos son los calculados.
                                       
                            if ERR<=Tolerancia:  #  El ciclo para si el error es menor a la tolerancia requerida.
                                break   
                                
                            

### Resultados ###
* Una vez el error entre la malla de datos supuestos y los calculados sea la requerida, el método llega a una convergencia. En este módulo se imprimen los resultados como número de iteraciones miníma, la matriz del sistema y el error en la convergencia.

In [198]:
print("TIPO DE APROXIMACIÓN CENTRADA")
print("___________________________________________")
print("Dimensión de la matriz del sistema = {}".format(NodosX),"x","{}".format(NodosY))
print("-------------------------------------------")
print("Cantidad de nodos totales = ", NodosX*NodosY)
print("-------------------------------------------")
np.set_printoptions(precision=2,suppress=True)
print("Matriz del sistema : ","\n",matriz) 
print("-------------------------------------------")
print("VALORES FRONTERA \n Norte-a = {}\n".format(a),"Sur-c = {}\n".format(c),"Oriente-b = {}\n".format(b),"Occidente-d = {}\n".format(d))
print("Número de iteraciones o convergencia = ",n-1)
print("-------------------------------------------")
print("Tolerancia = ", round(ERR,4))


# print(len(malla))

TIPO DE APROXIMACIÓN CENTRADA
___________________________________________
Dimensión de la matriz del sistema = 11 x 11
-------------------------------------------
Cantidad de nodos totales =  121
-------------------------------------------
Matriz del sistema :  
 [[0.39 0.5  0.54 0.56 0.56 0.57 0.57 0.57 0.57 0.57 0.43]
 [0.14 0.22 0.26 0.28 0.29 0.29 0.29 0.29 0.29 0.28 0.2 ]
 [0.05 0.1  0.12 0.14 0.14 0.15 0.15 0.15 0.15 0.14 0.1 ]
 [0.02 0.04 0.06 0.07 0.07 0.07 0.08 0.08 0.08 0.07 0.05]
 [0.01 0.02 0.03 0.03 0.04 0.04 0.04 0.04 0.04 0.04 0.02]
 [0.   0.01 0.01 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.01]
 [0.   0.   0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.   0.   0.   0.   0.   0.   0.   0.01 0.01 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]]
-------------------------------------------
VALORES FRONTERA 
 Norte-a = 1
 Sur-c = 0
 Oriente-b 